version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 10000
  producer:
    depends_on:
      - kafka
    build:
      context: ./transporter
    networks:
      - wikiflow-network
    volumes:
     - delta:/storage
     - ./stage:/stage/model
  consumer:
    depends_on:
      - kafka
    build:
      context: ./consumer
    networks:
      - wikiflow-network
    volumes:
     - delta:/storage
     - ./stage:/stage/model
  kafka:
    image: spotify/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_HOST: 127.0.0.1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - wikiflow-network
    volumes:
     - delta:/storage
     - ./stage:/stage/model
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=consumer
      - POSTGRES_DB=consumer
      - POSTGRES_PASSWORD=goto@Postgres1
    ports:
      - "5432:5432"
    networks:
      - wikiflow-network
    volumes:
     - delta:/storage
     - ./stage:/stage/model
networks:
  wikiflow-network:
    external:
      name: wikiflow-network
volumes:
   delta:
   stage:




